<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-13 17:18
=======
# Generated by Django 5.2.8 on 2025-11-12 16:13
>>>>>>> 3c917f3ac38c5e0a05fb49e109e2b119f4e2cab0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaderboardentry_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('assignment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('submission_correct', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('submisser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leaderboardentry')),
            ],
        ),
    ]
