# Generated by Django 5.2.7 on 2025-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_testcase_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
