FROM python:3.12-slim

WORKDIR /app

RUN apt-get update

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
