"""
Hardcoded test cases for problems.
Each entry maps a problem name to a list of test cases.
"""

TESTCASES = {
    "🌀 Welcome to the Chaos Sorting Challenge! 🌀": [
        {"input_data": [[1, 2]], "expected_output": "[1, 2]"},
        {"input_data": [[1, 2, 3]], "expected_output": "[3, 1, 2]"},
        {"input_data": [[3, 5, 3, 4, 7, 8]], "expected_output": "[3, 3, 4, 5, 8, 7]"},
        {"input_data": [[1, 9, 2, 8, 5, 4]], "expected_output": "[9, 8, 5, 4, 2, 1]"},
        {"input_data": [[10, 3, 5, 9, 2, 7, 3, 1]], "expected_output": "[3, 3, 10, 9, 5, 2, 1, 7]"},
        {"input_data": [[7, 3, 7, 3]], "expected_output": "[3, 3, 7, 7]"},
        {"input_data": [[]], "expected_output": "[]"},
        {"input_data": [[6, 4, 5, 4, 6]], "expected_output": "[4, 4, 5, 6, 6]"},
        {"input_data": [[100, 4, 1.5, 0.5, 42]], "expected_output": "[0.5, 1.5, 4, 42, 100]"},
        {"input_data": [[10, 5, 9, 2, 10, 5]], "expected_output": "[10, 10, 9, 5, 5, 2]"},
        {"input_data": [[15, 3, 20.5, 9, 7, 15, 3]], "expected_output": "[3, 3, 20.5, 15, 15, 9, 7]"},
        {"input_data": [[3, 9, 3]], "expected_output": "[3, 3, 9]"},
        {"input_data": [[7, 9, 7]], "expected_output": "[9, 7, 7]"},
        {"input_data": [[-1, -10, 9, 5]], "expected_output": "[9, 5, -1, -10]"},
        {"input_data": [[3, 7, 9, 3, 7, 9, 5, 5]], "expected_output": "[3, 3, 9, 9, 5, 5, 7, 7]"},
        {"input_data": [[12, 12, 9, 12]], "expected_output": "[12, 12, 12, 9]"},
        {"input_data": [[100, 3, 50, 9, 10, 7, 20, 3]], "expected_output": "[3, 3, 100, 50, 20, 10, 9, 7]"},
        {"input_data": [[0, 5, 9, 1]], "expected_output": "[9, 5, 1, 0]"},
        {"input_data": [[3, 7, 9, 3, 7]], "expected_output": "[3, 3, 9, 7, 7]"},
        {"input_data": [[1000.5, 9, 0.01, 50.2]], "expected_output": "[1000.5, 50.2, 9, 0.01]"},
        {"input_data": [[3, 7, 9]], "expected_output": "[3, 9, 7]"},
        {"input_data": [[2, 6, 9]], "expected_output": "[9, 6, 2]"},
        {"input_data": [[9, 9, 9]], "expected_output": "[9, 9, 9]"},
        {"input_data": [[9]], "expected_output": "[9]"},
        {"input_data": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], "expected_output": "[3, 9, 8, 6, 5, 4, 2, 1, 0, 7]"},
        {"input_data": [[8, 6, 4, 2, 9]], "expected_output": "[9, 8, 6, 4, 2]"},
        {"input_data": [[5, 5, 5, 9, 5, 5]], "expected_output": "[9, 5, 5, 5, 5, 5]"},
        {"input_data": [[1, -5, 9, 10, -10]], "expected_output": "[10, 9, 1, -5, -10]"},
        {"input_data": [[2, 1, 0, -1, 9]], "expected_output": "[9, 2, 1, 0, -1]"},
        {"input_data": [[4, 5, 6, 9]], "expected_output": "[9, 6, 5, 4]"},
        {"input_data": [[9, 1]], "expected_output": "[9, 1]"},
        {"input_data": [[1.1, 9, 1.2, 1.0]], "expected_output": "[9, 1.2, 1.1, 1.0]"},
        {"input_data": [[-5.5, 9, -6.5]], "expected_output": "[9, -5.5, -6.5]"},
        {"input_data": [[3, 10, 9, 3]], "expected_output": "[3, 3, 10, 9]"},
        {"input_data": [[7, 9, 7, 5]], "expected_output": "[9, 5, 7, 7]"},
        {"input_data": [[20, 15, 1, 10, 5]], "expected_output": "[1, 5, 10, 15, 20]"},
        {"input_data": [[-1, -10, 5]], "expected_output": "[-10, -1, 5]"},
        {"input_data": [[3, 7, 3, 7, 5, 5]], "expected_output": "[3, 3, 5, 5, 7, 7]"},
        {"input_data": [[12, 12, 12]], "expected_output": "[12, 12, 12]"},
        {"input_data": [[100, 50, 10, 7, 20]], "expected_output": "[10, 20, 50, 100, 7]"},
        {"input_data": [[0, 5, 1]], "expected_output": "[0, 1, 5]"},
        {"input_data": [[7, 7, 3, 3, 3]], "expected_output": "[3, 3, 3, 7, 7]"},
        {"input_data": [[1000.5, 0.01, 50.2]], "expected_output": "[0.01, 50.2, 1000.5]"},
        {"input_data": [[3, 7]], "expected_output": "[3, 7]"},
        {"input_data": [[4, 8]], "expected_output": "[4, 8]"},
        {"input_data": [[12]], "expected_output": "[12]"},
        {"input_data": [[0, 1, 2, 3, 4, 5, 6, 7, 8]], "expected_output": "[3, 0, 1, 2, 4, 5, 6, 8, 7]"},
        {"input_data": [[1, 2, 4, 5]], "expected_output": "[1, 2, 4, 5]"},
        {"input_data": [[5, 5, 5, 5, 5]], "expected_output": "[5, 5, 5, 5, 5]"},
        {"input_data": [[1, -5, 10, -10]], "expected_output": "[-10, -5, 1, 10]"},
        {"input_data": [[2, 1, 0, -1]], "expected_output": "[-1, 0, 1, 2]"},
        {"input_data": [[4, 5, 6]], "expected_output": "[4, 5, 6]"},
        {"input_data": [[1, 5]], "expected_output": "[1, 5]"},
        {"input_data": [[4, 1, 8, 5, 2, 6, 10, 30]], "expected_output": "[1, 2, 4, 5, 6, 8, 10, 30]"},
    ],
    "The Data Type Deluge": [
        {"input_data": [[5, 10.5, "clean", 3.0, 15, "data", 99.9, "mix", 1, 5.0, "type", 20, 0.1, "short"]], "expected_output": "{'Integers': 41, 'Floats': 2, 'Strings': 'clean-data-type-short'}"},
        {"input_data": [[-5, 5.0, "long", 3, "a", "", 5.1, 100]], "expected_output": "{'Integers': 98, 'Floats': 1, 'Strings': 'long'}"},
        {"input_data": [["test", "pass", "fail", "ok"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': 'test-pass-fail'}"},
        {"input_data": [[]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[10, -5, 0, 15, -20]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[5.0, 5.0001, 4.99, 10.0, -1.0]], "expected_output": "{'Integers': 0, 'Floats': 2, 'Strings': ''}"},
        {"input_data": [["four", "one", "two", "three", "five"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': 'four-three-five'}"},
        {"input_data": [["a", "bb", "ccc", "d"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[5, 5.0, "four", 4.0, 4, "ok", 6.0, "seven"]], "expected_output": "{'Integers': 9, 'Floats': 1, 'Strings': 'four-seven'}"},
        {"input_data": [[10, 0, -2, 7.1, 5.0, "zero", "one", "two", 8.8]], "expected_output": "{'Integers': 8, 'Floats': 2, 'Strings': 'zero'}"},
        {"input_data": [[3.14, 2.7, -1.0, 4.5, 5.0]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[100, 200, 300, 0]], "expected_output": "{'Integers': 600, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[1, "longstring", 10, "short", 100]], "expected_output": "{'Integers': 111, 'Floats': 0, 'Strings': 'longstring-short'}"},
        {"input_data": [["word", 6.1, "another", 3.3, "end"]], "expected_output": "{'Integers': 0, 'Floats': 1, 'Strings': 'word-another'}"},
        {"input_data": [[5.0, "abc", "d", 5.0]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[1, 2.0, [3], {"key": "value"}, "five", None, 6.0]], "expected_output": "{'Integers': 1, 'Floats': 1, 'Strings': 'five'}"},
        {"input_data": [["test", "test", "test", "no"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': 'test-test-test'}"},
        {"input_data": [[1000, 2000, 3000, -6000]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [["four-char", "long-string", 1.0, 10]], "expected_output": "{'Integers': 10, 'Floats': 0, 'Strings': 'four-char-long-string'}"},
        {"input_data": [[1.1, 2.2, 3.3, 4.4, 5.0]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[5.1, 6.2, 7.3, 8.4, 9.5]], "expected_output": "{'Integers': 0, 'Floats': 5, 'Strings': ''}"},
        {"input_data": [["x", "xx", "xxx", "xxxx"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': 'xxxx'}"},
        {"input_data": [[10, 20, 1.5, 2.5]], "expected_output": "{'Integers': 30, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[1000000, 2000000, "mega", 5.5]], "expected_output": "{'Integers': 3000000, 'Floats': 1, 'Strings': 'mega'}"},
        {"input_data": [[4, 4.0, "four", "word", 5.0, 5, 6.0, 6]], "expected_output": "{'Integers': 15, 'Floats': 1, 'Strings': 'four-word'}"},
        {"input_data": [[1, 1.1, "a", 10, 10.1, "ten_char", 100, 100.1, "hundred_char"]], "expected_output": "{'Integers': 111, 'Floats': 2, 'Strings': 'ten_char-hundred_char'}"},
        {"input_data": [[-1.0, -10.0, -5.5]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[-1, 1, 5.0, "abc", 4.9]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [["1234", 5, 5.1]], "expected_output": "{'Integers': 5, 'Floats': 1, 'Strings': '1234'}"},
        {"input_data": [[6.0, 7.0, 8.0, 9.0, 10.0]], "expected_output": "{'Integers': 0, 'Floats': 5, 'Strings': ''}"},
        {"input_data": [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], "expected_output": "{'Integers': 55, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[10, 10, 6.0, 6.0, "long", "long"]], "expected_output": "{'Integers': 20, 'Floats': 2, 'Strings': 'long-long'}"},
        {"input_data": [[5.0, "four", 5.1, "five"]], "expected_output": "{'Integers': 0, 'Floats': 1, 'Strings': 'four-five'}"},
        {"input_data": [[1, 2.0, "word", 6.0, True, False]], "expected_output": "{'Integers': 1, 'Floats': 1, 'Strings': 'word-word'}"},
        {"input_data": [["b", "a", "c", "d"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[3.0, 4.0, 5.0, 6.0, 7.0]], "expected_output": "{'Integers': 0, 'Floats': 2, 'Strings': ''}"},
        {"input_data": [[10, 5, 10.0, 5.0, "ten", "five"]], "expected_output": "{'Integers': 15, 'Floats': 1, 'Strings': 'five'}"},
        {"input_data": [[1.0, 2.0, 3.0, "a", "b", "c"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[1, 2, 3, "verylongstring", "anotherlong"]], "expected_output": "{'Integers': 6, 'Floats': 0, 'Strings': 'verylongstring-anotherlong'}"},
        {"input_data": [[6.1, 7.2, 8.3, "a", "b", "c"]], "expected_output": "{'Integers': 0, 'Floats': 3, 'Strings': ''}"},
        {"input_data": [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]], "expected_output": "{'Integers': 550, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [["alpha", "beta", "gamma", "delta", "epsilon"]], "expected_output": "{'Integers': 0, 'Floats': 0, 'Strings': 'alpha-beta-gamma-delta-epsilon'}"},
        {"input_data": [[5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0]], "expected_output": "{'Integers': 0, 'Floats': 10, 'Strings': ''}"},
        {"input_data": [[1, 5.1, "four", 2, 6.1, "five"]], "expected_output": "{'Integers': 3, 'Floats': 2, 'Strings': 'four-five'}"},
        {"input_data": [["word", 5.1, 1, 6.0, 2, "test", 7.0, 3, "long"]], "expected_output": "{'Integers': 6, 'Floats': 3, 'Strings': 'word-test-long'}"},
        {"input_data": [[4, 5, 6, 7, 8, 9, 10, 11, 12, 13]], "expected_output": "{'Integers': 85, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[10.1, 11.2, 12.3, 13.4, 14.5, 15.6]], "expected_output": "{'Integers': 0, 'Floats': 6, 'Strings': ''}"},
        {"input_data": [[-100, -200, -300]], "expected_output": "{'Integers': -600, 'Floats': 0, 'Strings': ''}"},
        {"input_data": [[-10.0, -1.0, 1.0, 5.0, 5.1, "test"]], "expected_output": "{'Integers': 0, 'Floats': 1, 'Strings': 'test'}"},
    ],
    "The Supply Chain Validator (String & List Logic)": [
        {"input_data": ["A1234, B-567, C9999, D-1234, E34, F-ABC, GHIJK, Z-XYZW, H-456"], "expected_output": "['A1234', 'B-567', 'C9999', 'F-ABC', 'GHIJK', 'H-456']"},
        {"input_data": ["A-123, Z99999, b1234, C-5678, X_Y_Z, A-B-C, W23456"], "expected_output": "['A-123', 'X_Y_Z', 'A-B-C']"},
        {"input_data": ["START, A-123, BCDFG, X-Y-Z"], "expected_output": "['START', 'A-123', 'BCDFG', 'X-Y-Z']"},
        {"input_data": [""], "expected_output": "[]"},
        {"input_data": ["A123, B-12, C123, D-12"], "expected_output": "[]"},
        {"input_data": ["A12345, B-12345, C12345, D-12345"], "expected_output": "[]"},
        {"input_data": ["K12345, L-123, M123, N-123456"], "expected_output": "['L-123']"},
        {"input_data": ["A1234, BCDFG, C5678, HIJKL"], "expected_output": "['A1234', 'C5678']"},
        {"input_data": ["a1234, X-Y-Z, c5678, B-C-D"], "expected_output": "['X-Y-Z', 'B-C-D']"},
        {"input_data": ["1ABCD, X-Y-Z, 9EFGH, B-C-D"], "expected_output": "['X-Y-Z', 'B-C-D']"},
        {"input_data": ["Z99999, -1234, aBCDE, A-BCD, B-CD-E, Y-Z-W"], "expected_output": "['-1234', 'A-BCD', 'Y-Z-W']"},
        {"input_data": ["TOPIC"], "expected_output": "['TOPIC']"},
        {"input_data": ["K1234, L-567"], "expected_output": "['K1234', 'L-567']"},
        {"input_data": [",A1234, B-567, C9999, D-123,"], "expected_output": "['B-567', 'D-123']"},
        {"input_data": ["A1234, XABCD, B5678, Y-EFG"], "expected_output": "['A1234', 'B5678', 'Y-EFG']"},
        {"input_data": ["a1234, B-567, C9999, d-123"], "expected_output": "['B-567', 'C9999', 'd-123']"},
        {"input_data": ["A-B-C, X-Y-Z, CDEFG, D-E-F"], "expected_output": "['A-B-C', 'X-Y-Z', 'CDEFG', 'D-E-F']"},
        {"input_data": ["A1234, -, B5678, -A"], "expected_output": "['A1234', 'B5678']"},
        {"input_data": ["A123, B-123, C123, D-123"], "expected_output": "['B-123', 'D-123']"},
        {"input_data": ["A12345, B-12345, C12345, D-12345"], "expected_output": "[]"},
        {"input_data": ["X-123, A1234, Z-567, C9999"], "expected_output": "['X-123', 'Z-567']"},
        {"input_data": ["VALID, X-Y-Z, YYYY, Z-Z-Z"], "expected_output": "['VALID', 'X-Y-Z', 'Z-Z-Z']"},
        {"input_data": ["A1234, 1-2-3, B5678, 4-5-6"], "expected_output": "['A1234', '1-2-3', 'B5678', '4-5-6']"},
        {"input_data": ["1-2-3, A1234"], "expected_output": "[]"},
        {"input_data": ["aBcDe, xYxYx, 1BcdE, XyXyX"], "expected_output": "[]"},
        {"input_data": ["A0000, B-123, C0000"], "expected_output": "['A0000', 'B-123', 'C0000']"},
        {"input_data": ["B-123, A0000, B-456"], "expected_output": "['B-123', 'B-456']"},
        {"input_data": ["VLD-A, V-A, A-V-A, X-VLD, VLD, X_X_X_X_X, Z12345, B-1-2-3-4"], "expected_output": "['VLD-A', 'A-V-A', 'X-VLD']"},
        {"input_data": ["A12, B-456, C789012, D-E-F"], "expected_output": "['B-456', 'D-E-F']"},
        {"input_data": ["A1234, X-Y, B5678, Z-ABCDEF"], "expected_output": "['A1234', 'B5678']"},
        {"input_data": [", A1234 , B-567 , C9999 ,"], "expected_output": "['B-567']"},
        {"input_data": ["A1234, ODDNO, C5678, NEXTO"], "expected_output": "['A1234', 'C5678']"},
        {"input_data": ["lower, X-Y-Z, small, B-C-D"], "expected_output": "['X-Y-Z', 'B-C-D']"},
        {"input_data": ["ALPHA, O-D-D, BETA, F-I-V"], "expected_output": "['ALPHA', 'O-D-D', 'F-I-V']"},
        {"input_data": ["A-B-C, ODD-1, X-Y-Z, ODD-2"], "expected_output": "['A-B-C', 'ODD-1', 'X-Y-Z', 'ODD-2']"},
        {"input_data": ["A1234, X-123, BCDFF, Y-456, C9999, Z-789, DEFFF, A-BC-"], "expected_output": "['A1234', 'X-123', 'BCDFF', 'Y-456', 'C9999', 'Z-789', 'DEFFF', 'A-BC-']"},
        {"input_data": ["A1234,, B-567"], "expected_output": "['A1234', 'B-567']"},
        {"input_data": ["ITEM1, NO-HY, ITEM3, YES-H"], "expected_output": "['ITEM1', 'NO-HY', 'ITEM3', 'YES-H']"},
        {"input_data": ["small, O-D-D, Large, E-V-E"], "expected_output": "['O-D-D', 'Large', 'E-V-E']"},
        {"input_data": ["HELLO, -, WORLD"], "expected_output": "['HELLO', 'WORLD']"},
        {"input_data": ["12345, X-Y-Z, 67890"], "expected_output": "['X-Y-Z']"},
        {"input_data": ["Zebra, A-123, Lion, B-456"], "expected_output": "['Zebra', 'A-123', 'B-456']"},
        {"input_data": ["A12, X-Y-Z-Z, BCD, Y-1-2-3"], "expected_output": "[]"},
        {"input_data": ["A12345, B-123, c1234, d-123"], "expected_output": "['B-123', 'd-123']"},
        {"input_data": ["ALPHA, -A, BETA, -B"], "expected_output": "['ALPHA']"},
        {"input_data": ["A, X-Y-Z, B, X-Y-Z"], "expected_output": "['X-Y-Z', 'X-Y-Z']"},
        {"input_data": ["A, XXXXX, B, YYYYY"], "expected_output": "[]"},
        {"input_data": ["A1234, X-Y-Z, aaaaa, b-b-b, CCCCC, 12345, FFFFF, Z-9-8, G-G-G, H-H-H"], "expected_output": "['A1234', 'X-Y-Z', 'b-b-b', 'CCCCC', 'FFFFF', 'Z-9-8', 'G-G-G', 'H-H-H']"},
        {"input_data": ["E0000, O-D-D, E0002, O-D-D, E0004, O-D-D, E0006, O-D-D"], "expected_output": "['E0000', 'O-D-D', 'E0002', 'O-D-D', 'E0004', 'O-D-D', 'E0006', 'O-D-D']"},
        {"input_data": [",A12345, X-Y-Z-W, B12345, Y-Z-W-X,"], "expected_output": "[]"},
        {"input_data": ["A0000, B0000, C0000, D0000, E0000"], "expected_output": "['A0000', 'C0000', 'E0000']"},
        {"input_data": ["a0000, B-0-0, c0000, D-0-0, e0000"], "expected_output": "['B-0-0', 'D-0-0']"},
        {"input_data": ["A000, B-000000, C000, D-000000, E000"], "expected_output": "[]"},
    ],
    "The Time-Warp Transaction Auditor": [
        {"input_data": [[10, 20, 15, 25, 25, 40, 35, 50, 50]], "expected_output": "{'Valid_Unique_Timestamps': [10, 20, 40], 'Problematic_Duplicates': [50, 25]}"},
        {"input_data": [[100, 110, 105, 120, 130, 125]], "expected_output": "{'Valid_Unique_Timestamps': [100, 110, 120, 130], 'Problematic_Duplicates': []}"},
        {"input_data": [[5, 10, 10, 15, 15, 20, 20]], "expected_output": "{'Valid_Unique_Timestamps': [5], 'Problematic_Duplicates': [20, 15, 10]}"},
        {"input_data": [[]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 2, 3]], "expected_output": "{'Valid_Unique_Timestamps': [1, 3], 'Problematic_Duplicates': [2]}"},
        {"input_data": [[1, 5, 10, 15, 15, 20, 18, 22, 22]], "expected_output": "{'Valid_Unique_Timestamps': [1, 5, 10, 20], 'Problematic_Duplicates': [22, 15]}"},
        {"input_data": [[1, 2, 3, 4, 5]], "expected_output": "{'Valid_Unique_Timestamps': [1, 2, 3, 4, 5], 'Problematic_Duplicates': []}"},
        {"input_data": [[100, 90, 80, 70]], "expected_output": "{'Valid_Unique_Timestamps': [100], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 3, 2, 5, 4, 7]], "expected_output": "{'Valid_Unique_Timestamps': [1, 3, 5, 7], 'Problematic_Duplicates': []}"},
        {"input_data": [[10, 10, 20, 30]], "expected_output": "{'Valid_Unique_Timestamps': [20, 30], 'Problematic_Duplicates': [10]}"},
        {"input_data": [[5, 10, 5, 15]], "expected_output": "{'Valid_Unique_Timestamps': [10, 15], 'Problematic_Duplicates': [5]}"},
        {"input_data": [[1, 1, 1, 1, 1]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': [1]}"},
        {"input_data": [[2, 1, 3, 1, 4, 1]], "expected_output": "{'Valid_Unique_Timestamps': [2, 3, 4], 'Problematic_Duplicates': [1]}"},
        {"input_data": [[5, 10, 10, 10, 20, 20, 30]], "expected_output": "{'Valid_Unique_Timestamps': [5, 30], 'Problematic_Duplicates': [20, 10]}"},
        {"input_data": [[10, 20, 20, 30, 30]], "expected_output": "{'Valid_Unique_Timestamps': [10], 'Problematic_Duplicates': [30, 20]}"},
        {"input_data": [[10, 20, 15, 25, 30]], "expected_output": "{'Valid_Unique_Timestamps': [10, 20, 25, 30], 'Problematic_Duplicates': []}"},
        {"input_data": [[10, 20, 20, 10]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': [20, 10]}"},
        {"input_data": [[4, 6, 5, 8, 7]], "expected_output": "{'Valid_Unique_Timestamps': [4, 6, 8], 'Problematic_Duplicates': []}"},
        {"input_data": [[-5, 0, -1, 5, 10]], "expected_output": "{'Valid_Unique_Timestamps': [-5, 0, 5, 10], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 3, 4, 3, 5]], "expected_output": "{'Valid_Unique_Timestamps': [1, 2, 4, 5], 'Problematic_Duplicates': [3]}"},
        {"input_data": [[1000, 2000, 1500, 3000]], "expected_output": "{'Valid_Unique_Timestamps': [1000, 2000, 3000], 'Problematic_Duplicates': []}"},
        {"input_data": [[99, 100, 101, 100]], "expected_output": "{'Valid_Unique_Timestamps': [99, 101], 'Problematic_Duplicates': [100]}"},
        {"input_data": [[1, 5, 10, 2, 15]], "expected_output": "{'Valid_Unique_Timestamps': [1, 5, 10, 15], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 3, 3, 4]], "expected_output": "{'Valid_Unique_Timestamps': [1, 2, 4], 'Problematic_Duplicates': [3]}"},
        {"input_data": [[10, 20, 19, 30, 29, 40]], "expected_output": "{'Valid_Unique_Timestamps': [10, 20, 30, 40], 'Problematic_Duplicates': []}"},
        {"input_data": [[2, 5, 7, 1, 9, 11]], "expected_output": "{'Valid_Unique_Timestamps': [2, 5, 7, 9, 11], 'Problematic_Duplicates': []}"},
        {"input_data": [[3, 3, 4, 4, 5, 5]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': [5, 4, 3]}"},
        {"input_data": [[100, 200, 100, 300, 300, 400]], "expected_output": "{'Valid_Unique_Timestamps': [200, 400], 'Problematic_Duplicates': [300, 100]}"},
        {"input_data": [[5, 15, 10, 25, 20]], "expected_output": "{'Valid_Unique_Timestamps': [5, 15, 25], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 3, 2, 4, 3]], "expected_output": "{'Valid_Unique_Timestamps': [1, 4], 'Problematic_Duplicates': [3, 2]}"},
        {"input_data": [[-10, -5, -8, -2, 0]], "expected_output": "{'Valid_Unique_Timestamps': [-10, -5, -2, 0], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 3, 4, 5, 4, 3, 2, 1]], "expected_output": "{'Valid_Unique_Timestamps': [5], 'Problematic_Duplicates': [4, 3, 2, 1]}"},
        {"input_data": [[5, 10, 15, 15, 20, 25, 20]], "expected_output": "{'Valid_Unique_Timestamps': [5, 10, 25], 'Problematic_Duplicates': [20, 15]}"},
        {"input_data": [[1, 1, 2, 2, 3, 3]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': [3, 2, 1]}"},
        {"input_data": [[5, 10, 15, 20, 10, 25]], "expected_output": "{'Valid_Unique_Timestamps': [5, 15, 20, 25], 'Problematic_Duplicates': [10]}"},
        {"input_data": [[10000, 10001, 10000]], "expected_output": "{'Valid_Unique_Timestamps': [10001], 'Problematic_Duplicates': [10000]}"},
        {"input_data": [[10, 12, 11, 13, 12]], "expected_output": "{'Valid_Unique_Timestamps': [10, 13], 'Problematic_Duplicates': [12]}"},
        {"input_data": [[7, 8, 9, 10, 9, 11]], "expected_output": "{'Valid_Unique_Timestamps': [7, 8, 10, 11], 'Problematic_Duplicates': [9]}"},
        {"input_data": [[1, 5, 10, 15, 20, 25]], "expected_output": "{'Valid_Unique_Timestamps': [1, 5, 10, 15, 20, 25], 'Problematic_Duplicates': []}"},
        {"input_data": [[30, 30, 35, 35, 40, 40]], "expected_output": "{'Valid_Unique_Timestamps': [], 'Problematic_Duplicates': [40, 35, 30]}"},
        {"input_data": [[1, 5, 1, 10, 1, 15]], "expected_output": "{'Valid_Unique_Timestamps': [5, 10, 15], 'Problematic_Duplicates': [1]}"},
        {"input_data": [[1, 2, 2, 3, 3, 4, 4]], "expected_output": "{'Valid_Unique_Timestamps': [1], 'Problematic_Duplicates': [4, 3, 2]}"},
        {"input_data": [[10, 20, 10, 30, 40, 30]], "expected_output": "{'Valid_Unique_Timestamps': [20, 40], 'Problematic_Duplicates': [30, 10]}"},
        {"input_data": [[10, 15, 20, 25, 30, 28]], "expected_output": "{'Valid_Unique_Timestamps': [10, 15, 20, 25, 30], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], "expected_output": "{'Valid_Unique_Timestamps': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 1, 2, 3, 4, 5, 6, 7, 8, 9]], "expected_output": "{'Valid_Unique_Timestamps': [2, 3, 4, 5, 6, 7, 8, 9], 'Problematic_Duplicates': [1]}"},
        {"input_data": [[2, 1, 3, 2, 4, 3, 5, 4]], "expected_output": "{'Valid_Unique_Timestamps': [5], 'Problematic_Duplicates': [4, 3, 2]}"},
        {"input_data": [[0, 1, 0, 2, 0, 3]], "expected_output": "{'Valid_Unique_Timestamps': [1, 2, 3], 'Problematic_Duplicates': [0]}"},
        {"input_data": [[1, 5, 10, 10, 15, 20, 20, 25]], "expected_output": "{'Valid_Unique_Timestamps': [1, 5, 15, 25], 'Problematic_Duplicates': [20, 10]}"},
        {"input_data": [[10, 5, 20, 15, 30, 25]], "expected_output": "{'Valid_Unique_Timestamps': [10, 20, 30], 'Problematic_Duplicates': []}"},
        {"input_data": [[1, 10, 100, 1000, 10000]], "expected_output": "{'Valid_Unique_Timestamps': [1, 10, 100, 1000, 10000], 'Problematic_Duplicates': []}"},
    ],
    "The Code String Deconstruction": [
        {"input_data": ["A1B2C3"], "expected_output": "['cba', 18]"},
        {"input_data": ["Z9Y8X7"], "expected_output": "['xyz', 72]"},
        {"input_data": ["C0D1E2F3"], "expected_output": "['fedc', 24]"},
        {"input_data": ["G5H5I5J5"], "expected_output": "['jihg', 80]"},
        {"input_data": ["K1L9M1N9"], "expected_output": "['nmlk', 80]"},
        {"input_data": ["T2E4S6T8"], "expected_output": "['tset', 80]"},
        {"input_data": ["Q1W1E1R1T1"], "expected_output": "['trewq', 25]"},
        {"input_data": ["P9H9O9N9E9"], "expected_output": "['enohp', 225]"},
        {"input_data": ["J1U2M3P4S5"], "expected_output": "['spmuj', 75]"},
        {"input_data": ["V8I7D6E5O4"], "expected_output": "['oediv', 150]"},
        {"input_data": ["L1O2N3G4E5R6"], "expected_output": "['regnol', 126]"},
        {"input_data": ["X9Y9Z9A9B9C9"], "expected_output": "['cbaZYX'.lower(), 324]"},
        {"input_data": ["D1E2C3O4D5E6R7"], "expected_output": "['reDOCED'.lower(), 196]"},
        {"input_data": ["F0O0R0Z0E0R0O0"], "expected_output": "['orezrof', 0]"},
        {"input_data": ["G8A7M6E5O4V3E2R1"], "expected_output": "['revOEmag'.lower(), 288]"},
        {"input_data": ["H1I1J1K1L1M1N1"], "expected_output": "['nmlkjih', 49]"},
        {"input_data": ["a1b1c1d1e1f1"], "expected_output": "['fedcba', 36]"},
        {"input_data": ["R9E8V7I6S5E4D3"], "expected_output": "['dEsIvEr'.lower(), 294]"},
        {"input_data": ["M3A3T3R3I3X3"], "expected_output": "['xirtam', 108]"},
        {"input_data": ["W1O2R3K4I5N6G7"], "expected_output": "['gniKroW'.lower(), 196]"},
        {"input_data": ["A1B9C1D9"], "expected_output": "['dcbA'.lower(), 80]"},
        {"input_data": ["E0F9G0H9"], "expected_output": "['hGfE'.lower(), 72]"},
        {"input_data": ["I3J7K3L7"], "expected_output": "['lKjI'.lower(), 80]"},
        {"input_data": ["M5N5O5P5Q5"], "expected_output": "['qPoNm'.lower(), 125]"},
        {"input_data": ["R0S0T0U0V0"], "expected_output": "['vutSr'.lower(), 0]"},
        {"input_data": ["W1E1B1C1A1M1"], "expected_output": "['macbew', 36]"},
        {"input_data": ["D2A4T6A8"], "expected_output": "['atad', 80]"},
        {"input_data": ["F9I9L9E9"], "expected_output": "['elif', 144]"},
        {"input_data": ["G1H2I3J4K5L6M7"], "expected_output": "['mlkjihg', 196]"},
        {"input_data": ["N8O8P8Q8R8S8"], "expected_output": "['srqpon', 288]"},
        {"input_data": ["H1e2L3l4O5"], "expected_output": "['oLlEh'.lower(), 75]"},
        {"input_data": ["W9o8R7l6D5"], "expected_output": "['dLrOw'.lower(), 175]"},
        {"input_data": ["P1y2T3h4O5n6"], "expected_output": "['nOhTyP'.lower(), 126]"},
        {"input_data": ["J4a3V2a1"], "expected_output": "['aVaJ'.lower(), 40]"},
        {"input_data": ["S2h4O6e8S1"], "expected_output": "['sEoHs'.lower(), 105]"},
        {"input_data": ["B7o6O5k4"], "expected_output": "['kOoB'.lower(), 88]"},
        {"input_data": ["C9a8T7"], "expected_output": "['tAc'.lower(), 72]"},
        {"input_data": ["D1o2G3"], "expected_output": "['gOd'.lower(), 18]"},
        {"input_data": ["M3O4U5S6E7"], "expected_output": "['eSuOm'.lower(), 125]"},
        {"input_data": ["A1B1C1D1E1F1G1H1I1J1"], "expected_output": "['jihgfEdcba'.lower(), 100]"},
        {"input_data": ["A9B9C9D9E9F9G9H9I9J9"], "expected_output": "['jihgfedcba', 900]"},
        {"input_data": ["K1L2M3N4O5P6Q7R8S9T1"], "expected_output": "['tSrQpOnMlK'.lower(), 460]"},
        {"input_data": ["U2V4W6X8Y1Z3A5B7C9"], "expected_output": "['cBaZyXwVu'.lower(), 405]"},
        {"input_data": ["T1E1S1T1S1H1E1R1E1"], "expected_output": "['eReHsTsEt'.lower(), 81]"},
        {"input_data": ["X0Y1X2Y3X4Y5"], "expected_output": "['yXyXyX'.lower(), 90]"},
        {"input_data": ["M1A2X3P4E5R6I7O8D9"], "expected_output": "['doIrEpxAm'.lower(), 405]"},
        {"input_data": ["A1L1T1E1R1N1A1T1E1"], "expected_output": "['eTaNrEtLa'.lower(), 81]"},
        {"input_data": ["Z9E8R7O6S5"], "expected_output": "['sOrEz'.lower(), 175]"},
        {"input_data": ["O1N2E3H4U5N6D7R8E9D0"], "expected_output": "['dErDnUhEnO'.lower(), 450]"},
    ],
    "The Temperature Stability Tracker": [
        {"input_data": [[20, 21, 23, 27, 26, 25, 27], 2], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 4}, {'Type': 'Stable Period', 'Index': 6, 'Length': 4}]"},
        {"input_data": [[1, 2, 3, 5, 4, 3, 5], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Stable Period', 'Index': 5, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 6, 'Magnitude': 2}]"},
        {"input_data": [[10, 12, 14, 15, 17, 18, 20], 3], "expected_output": "[{'Type': 'Stable Period', 'Index': 6, 'Length': 7}]"},
        {"input_data": [[10, 15, 16, 17, 18], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 5}, {'Type': 'Stable Period', 'Index': 4, 'Length': 4}]"},
        {"input_data": [[5, 6], 1], "expected_output": "[]"},
        {"input_data": [[5, 6, 7], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}]"},
        {"input_data": [[10, 10, 10, 11, 11, 11], 0], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 1}, {'Type': 'Stable Period', 'Index': 5, 'Length': 3}]"},
        {"input_data": [[], 5], "expected_output": "[]"},
        {"input_data": [[5, 10, 8, 11, 9], 2], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 5}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 3}]"},
        {"input_data": [[1, 2, 3, 5, 6], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}]"},
        {"input_data": [[1, 3, 5, 7, 9], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}]"},
        {"input_data": [[1, 2, 3, 4, 3, 2, 1], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 6, 'Length': 7}]"},
        {"input_data": [[10, 12, 14, 17, 18, 19, 21], 2], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 3}, {'Type': 'Stable Period', 'Index': 6, 'Length': 4}]"},
        {"input_data": [[10, 13, 16, 17, 18], 3], "expected_output": "[{'Type': 'Stable Period', 'Index': 4, 'Length': 5}]"},
        {"input_data": [[10, 14, 18, 19, 20], 3], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 4}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 4}, {'Type': 'Stable Period', 'Index': 4, 'Length': 3}]"},
        {"input_data": [[10, 10, 10, 11, 12, 13], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 11, 13, 14, 16, 17], 2], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[1, 2, 4, 6, 8, 10], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[5, 7, 9, 11, 13], 3], "expected_output": "[{'Type': 'Stable Period', 'Index': 4, 'Length': 5}]"},
        {"input_data": [[5, 9, 13, 17, 21], 3], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 4}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 4}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 4}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 4}]"},
        {"input_data": [[10, 11, 12, 14, 15, 16, 17], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Stable Period', 'Index': 6, 'Length': 4}]"},
        {"input_data": [[10, 11, 13, 14, 15, 17, 18], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Stable Period', 'Index': 4, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[10, 13, 14, 15, 18, 19], 2], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 3}, {'Type': 'Stable Period', 'Index': 3, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 3}]"},
        {"input_data": [[5, 5, 5, 5, 6, 7], 0], "expected_output": "[{'Type': 'Stable Period', 'Index': 3, 'Length': 4}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 1}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 1}]"},
        {"input_data": [[1, 1, 1, 2, 2, 2], 0], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 1}, {'Type': 'Stable Period', 'Index': 5, 'Length': 3}]"},
        {"input_data": [[1, 1, 2, 2, 3, 3], 0], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 1}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 1}]"},
        {"input_data": [[5, 4, 3, 10, 9, 8], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 7}, {'Type': 'Stable Period', 'Index': 5, 'Length': 3}]"},
        {"input_data": [[10, 10, 11, 12, 11, 10], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 9, 8, 10, 12, 14], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[1, 10, 20, 30], 5], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 9}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 10}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 10}]"},
        {"input_data": [[10, 13, 16, 17, 14, 11], 3], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[1, 5, 9, 10, 11], 4], "expected_output": "[{'Type': 'Stable Period', 'Index': 4, 'Length': 5}]"},
        {"input_data": [[10, 15, 20], 4], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 5}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 5}]"},
        {"input_data": [[0, 1, 0, 1, 0, 1], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[0, 2, 0, 2, 0, 2], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[1, 10, 1, 10, 1, 10], 8], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 9}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 9}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 9}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 9}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 9}]"},
        {"input_data": [[1, 10, 1, 10, 1, 10], 9], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[-5, -4, -3, -1, 0], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}]"},
        {"input_data": [[-10, -5, 0, 5, 10], 4], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 5}, {'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 5}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 5}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 5}]"},
        {"input_data": [[-10, -9, -8, -7, -8, -9], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 11, 12, 13, 14, 15, 16], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 6, 'Length': 7}]"},
        {"input_data": [[5, 4, 3, 2, 1, 0], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 10, 9, 8, 7, 6], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 11, 12], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}]"},
        {"input_data": [[10, 11, 13], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}]"},
        {"input_data": [[10, 12, 14, 16], 2], "expected_output": "[{'Type': 'Stable Period', 'Index': 3, 'Length': 4}]"},
        {"input_data": [[10, 12, 15, 17], 2], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 3}]"},
        {"input_data": [[5, 6, 8, 9, 10, 12], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Stable Period', 'Index': 4, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[10, 11, 12, 13, 15, 14], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 3, 'Length': 4}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}]"},
        {"input_data": [[2, 2, 2, 2, 1, 3], 0], "expected_output": "[{'Type': 'Stable Period', 'Index': 3, 'Length': 4}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 1}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[10, 10, 10, 15, 15, 15], 4], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 5}, {'Type': 'Stable Period', 'Index': 5, 'Length': 3}]"},
        {"input_data": [[1, 3, 2, 4, 3, 5], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 1, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[100, 100, 100, 100], 0], "expected_output": "[{'Type': 'Stable Period', 'Index': 3, 'Length': 4}]"},
        {"input_data": [[1, 2, 3, 5, 4, 6], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 2, 'Length': 3}, {'Type': 'Rapid Change', 'Index': 3, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 5, 'Magnitude': 2}]"},
        {"input_data": [[1, 1, 2, 3, 4, 5], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 5, 'Length': 6}]"},
        {"input_data": [[10, 11, 13, 14, 16], 1], "expected_output": "[{'Type': 'Rapid Change', 'Index': 2, 'Magnitude': 2}, {'Type': 'Rapid Change', 'Index': 4, 'Magnitude': 2}]"},
        {"input_data": [[10, 10, 11, 10, 11], 1], "expected_output": "[{'Type': 'Stable Period', 'Index': 4, 'Length': 5}]"},
    ],
    "The Resource Allocation Optimizer (Knapsack Variant)": [
        {"input_data": [[], 10], "expected_output": "0"},
        {"input_data": [[[1, 10]], 0], "expected_output": "0"},
        {"input_data": [[[10, 10]], 5], "expected_output": "0"},
        {"input_data": [[[0, 10], [5, 5]], 5], "expected_output": "15"},
        {"input_data": [[[5, 0], [5, 5]], 10], "expected_output": "5"},
        {"input_data": [[[3, 30], [4, 50]], 7], "expected_output": "80"},
        {"input_data": [[[3, 30], [4, 50]], 6], "expected_output": "50"},
        {"input_data": [[[2, 10], [2, 10]], 3], "expected_output": "10"},
        {"input_data": [[[1, 1], [1, 2], [1, 3]], 2], "expected_output": "5"},
        {"input_data": [[[10, 100]], 10], "expected_output": "100"},
        {"input_data": [[[10, 100], [10, 101]], 10], "expected_output": "101"},
        {"input_data": [[[4, 10], [5, 12], [3, 8]], 8], "expected_output": "20"},
        {"input_data": [[[10, 10], [1, 1]], 9], "expected_output": "1"},
        {"input_data": [[[1, 2], [1, 2], [1, 2], [1, 2]], 3], "expected_output": "6"},
        {"input_data": [[[7, 4], [5, 3], [1, 10]], 6], "expected_output": "13"},
        {"input_data": [[[3, 30], [4, 50], [5, 60]], 8], "expected_output": "90"},
        {"input_data": [[[4, 12], [2, 2], [1, 1], [1, 4]], 8], "expected_output": "19"},
        {"input_data": [[[10, 100], [3, 50], [7, 60]], 10], "expected_output": "110"},
        {"input_data": [[[2, 10], [2, 10], [2, 10], [2, 10]], 7], "expected_output": "30"},
        {"input_data": [[[5, 10], [1, 1], [1, 1], [1, 1], [1, 1]], 5], "expected_output": "10"},
        {"input_data": [[[15, 15], [10, 10], [5, 5]], 20], "expected_output": "20"},
        {"input_data": [[[1, 1], [1, 1], [20, 100]], 21], "expected_output": "101"},
        {"input_data": [[[10, 10], [10, 10], [10, 10]], 25], "expected_output": "20"},
        {"input_data": [[[5, 10], [10, 15], [15, 20]], 16], "expected_output": "25"},
        {"input_data": [[[1, 10], [1, 10], [3, 10], [3, 10]], 6], "expected_output": "30"},
        {"input_data": [[[12, 4], [1, 2], [4, 10], [1, 1], [2, 2]], 15], "expected_output": "15"},
        {"input_data": [[[20, 50], [20, 50], [10, 10]], 40], "expected_output": "100"},
        {"input_data": [[[10, 10], [10, 100], [10, 10]], 20], "expected_output": "110"},
        {"input_data": [[[5, 50], [6, 50], [10, 50]], 11], "expected_output": "100"},
        {"input_data": [[[1, 10], [1, 10], [1, 10], [1, 10], [1, 10]], 10], "expected_output": "50"},
        {"input_data": [[[3, 5], [3, 5], [3, 5], [1, 10]], 9], "expected_output": "20"},
        {"input_data": [[[1, 100], [100, 100]], 100], "expected_output": "100"},
        {"input_data": [[[1, 10], [2, 20], [3, 30], [4, 40], [5, 50]], 10], "expected_output": "100"},
        {"input_data": [[[100, 100], [1, 10]], 99], "expected_output": "10"},
        {"input_data": [[[50, 50], [50, 50]], 49], "expected_output": "0"},
        {"input_data": [[[10, 100], [1, 10]], 10], "expected_output": "100"},
        {"input_data": [[[10, 100], [1, 11], [1, 11]], 11], "expected_output": "111"},
        {"input_data": [[[10, 100], [1, 11], [1, 11], [1, 11], [1, 11]], 10], "expected_output": "100"},
        {"input_data": [[[5, 100], [6, 101]], 10], "expected_output": "101"},
        {"input_data": [[[1, 5], [1, 5], [1, 5], [1, 5], [1, 5]], 2], "expected_output": "10"},
        {"input_data": [[[5, 10], [5, 10], [5, 10], [5, 10]], 12], "expected_output": "20"},
        {"input_data": [[[1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6]], 4], "expected_output": "18"},
        {"input_data": [[[10, 40], [20, 50], [30, 60], [40, 70]], 50], "expected_output": "110"},
        {"input_data": [[[10, 10], [10, 10], [10, 10]], 30], "expected_output": "30"},
        {"input_data": [[[10, 10], [10, 10], [10, 10]], 31], "expected_output": "30"},
        {"input_data": [[[2, 3], [3, 4], [4, 5], [5, 8], [9, 10]], 10], "expected_output": "15"},
        {"input_data": [[[8, 10], [5, 7], [12, 16], [4, 5]], 20], "expected_output": "26"},
        {"input_data": [[[30, 60], [10, 10], [20, 50], [40, 80]], 60], "expected_output": "130"},
        {"input_data": [[[7, 80], [15, 150], [2, 20], [1, 10]], 10], "expected_output": "110"},
        {"input_data": [[[10, 10], [10, 10], [10, 10], [10, 10], [10, 10]], 45], "expected_output": "40"},
    ],
    "The Longest Non-Overlapping Subsequence": [
        {"input_data": ["abcxyzabcxyz"], "expected_output": "'abcxyz'"},
        {"input_data": ["12341234"], "expected_output": "'1234'"},
        {"input_data": ["aabbaaabbaa"], "expected_output": "'aabba'"},
        {"input_data": ["ababcdababcd"], "expected_output": "'ababcd'"},
        {"input_data": ["1234512345"], "expected_output": "'12345'"},
        {"input_data": ["topcoderistopcoder"], "expected_output": "'topcoder'"},
        {"input_data": ["ab_cd_efab_cd_ef"], "expected_output": "'ab_cd_ef'"},
        {"input_data": ["QWERTYuiopQWERTYuiop"], "expected_output": "'QWERTYuiop'"},
        {"input_data": ["01100110"], "expected_output": "'0110'"},
        {"input_data": ["zyxwvuzyxwvu"], "expected_output": "'zyxwvu'"},
        {"input_data": ["abcabdeab"], "expected_output": "'ab'"},
        {"input_data": ["mississippi"], "expected_output": "'iss'"},
        {"input_data": ["applepieapple"], "expected_output": "'apple'"},
        {"input_data": ["hellohellohello"], "expected_output": "'hello'"},
        {"input_data": ["abracadabra"], "expected_output": "'abra'"},
        {"input_data": ["test_test_test"], "expected_output": "'test_'"},
        {"input_data": ["programming"], "expected_output": "'r'"},
        {"input_data": ["abcdefabghijab"], "expected_output": "'ab'"},
        {"input_data": ["AAAA"], "expected_output": "'AA'"},
        {"input_data": ["AAAAA"], "expected_output": "'AA'"},
        {"input_data": ["AAAAAAAA"], "expected_output": "'AAAA'"},
        {"input_data": ["ABABABAB"], "expected_output": "'ABAB'"},
        {"input_data": ["ababab"], "expected_output": "'ab'"},
        {"input_data": ["1010101010"], "expected_output": "'1010'"},
        {"input_data": ["aaabbbccc"], "expected_output": "'a'"},
        {"input_data": ["zzzaaa"], "expected_output": "'z'"},
        {"input_data": ["xoxoxtryxoxox"], "expected_output": "'xoxox'"},
        {"input_data": ["abcdefa"], "expected_output": "'a'"},
        {"input_data": ["zyxwvuzy"], "expected_output": "'zy'"},
        {"input_data": ["a_b_c_d_a"], "expected_output": "'a'"},
        {"input_data": ["pqrstuvwpqrstuvwxyz"], "expected_output": "'pqrstuvw'"},
        {"input_data": ["aabbcceeaabbcce"], "expected_output": "'aabbcce'"},
        {"input_data": ["12345671234567"], "expected_output": "'1234567'"},
        {"input_data": ["The quick brown fox jumps over the lazy dog."], "expected_output": "'he '"},
        {"input_data": ["abacaba"], "expected_output": "'aba'"},
        {"input_data": ["abcde"], "expected_output": "''"},
        {"input_data": ["a"], "expected_output": "''"},
        {"input_data": [""], "expected_output": "''"},
        {"input_data": ["abccba"], "expected_output": "'a'"},
        {"input_data": ["123321"], "expected_output": "'1'"},
        {"input_data": ["abcdefghijklmnopqrstuvwxyz"], "expected_output": "''"},
        {"input_data": ["hannah"], "expected_output": "'h'"},
        {"input_data": ["123454321"], "expected_output": "'1'"},
        {"input_data": ["abCdEfG"], "expected_output": "''"},
    ],
    "The Array Partition Optimizer": [
        {"input_data": [[5, 10]], "expected_output": "[1, 5.00]"},
        {"input_data": [[1, 100]], "expected_output": "[1, 1.00]"},
        {"input_data": [[100, 1]], "expected_output": "[1, 100.00]"},
        {"input_data": [[1, 1, 1]], "expected_output": "[1, 1.00]"},
        {"input_data": [[10, 20, 30, 40]], "expected_output": "[3, 20.00]"},
        {"input_data": [[1, 5, 1, 5]], "expected_output": "[3, 2.33]"},
        {"input_data": [[10, 10, 10, 1]], "expected_output": "[3, 10.00]"},
        {"input_data": [[100, 1, 1, 1, 1]], "expected_output": "[4, 25.75]"},
        {"input_data": [[1, 1, 1, 1, 100]], "expected_output": "[4, 1.00]"},
        {"input_data": [[1, 2, 3, 4, 100]], "expected_output": "[4, 2.50]"},
        {"input_data": [[50, 1, 1, 100]], "expected_output": "[3, 17.33]"},
        {"input_data": [[10, 1, 10, 1]], "expected_output": "[3, 7.0]"},
        {"input_data": [[10, 1, 1, 10]], "expected_output": "[3, 4.0]"},
        {"input_data": [[1, 10, 100, 1000]], "expected_output": "[3, 37.0]"},
        {"input_data": [[1, 2, 10, 1]], "expected_output": "[3, 4.33]"},
        {"input_data": [[5, 5, 15, 15]], "expected_output": "[2, 5.00]"},
        {"input_data": [[5, 10, 15, 20]], "expected_output": "[3, 10.00]"},
        {"input_data": [[20, 15, 10, 5]], "expected_output": "[3, 15.0]"},
        {"input_data": [[1, 100, 1, 100]], "expected_output": "[3, 34.0]"},
        {"input_data": [[7, 7, 7, 7, 7]], "expected_output": "[1, 7.00]"},
        {"input_data": [[10, 10, 10, 10, 10, 10]], "expected_output": "[1, 10.00]"},
        {"input_data": [[2, 4, 2, 4, 2, 4]], "expected_output": "[5, 2.80]"},
        {"input_data": [[1, 1, 10, 10, 1, 1]], "expected_output": "[5, 4.6]"},
        {"input_data": [[1, 1, 1, 1, 1, 1, 1, 1, 100]], "expected_output": "[8, 1.00]"},
        {"input_data": [[100, 1, 1, 1, 1, 1, 1, 1, 1]], "expected_output": "[8, 13.38]"},
        {"input_data": [[10, 1, 1, 10, 1, 1, 10, 1, 1]], "expected_output": "[8, 4.38]"},
        {"input_data": [[1000, 1000, 1000, 1, 1]], "expected_output": "[4, 750.25]"},
        {"input_data": [[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]], "expected_output": "[9, 500.00]"},
        {"input_data": [[1, 2, 3, 4, 5]], "expected_output": "[4, 2.50]"},
        {"input_data": [[1, 1, 1, 2]], "expected_output": "[3, 1.00]"},
        {"input_data": [[10, 10, 1, 1]], "expected_output": "[3, 7.0]"},
        {"input_data": [[1, 1, 1, 100]], "expected_output": "[3, 1.00]"},
        {"input_data": [[1, 2, 3, 4]], "expected_output": "[3, 2.00]"},
        {"input_data": [[1, 1, 1, 1, 5, 5, 5]], "expected_output": "[4, 1.00]"},
        {"input_data": [[1, 5, 5, 5, 1]], "expected_output": "[4, 4.0]"},
        {"input_data": [[1, 1, 1, 50, 50]], "expected_output": "[3, 1.00]"},
        {"input_data": [[50, 50, 1, 1, 1]], "expected_output": "[4, 25.5]"},
        {"input_data": [[10, 1, 2, 3, 4]], "expected_output": "[4, 4.0]"},
        {"input_data": [[1, 1, 1, 100, 1]], "expected_output": "[4, 25.75]"},
        {"input_data": [[1, 5, 8, 2, 9, 3]], "expected_output": "[5, 5.0]"},
        {"input_data": [[1, 10, 1, 10, 1]], "expected_output": "[4, 5.5]"},
        {"input_data": [[10, 1, 10, 1, 10]], "expected_output": "[4, 5.5]"},
        {"input_data": [[1, 1, 1, 1, 1, 100, 1000]], "expected_output": "[6, 17.5]"},
        {"input_data": [[2, 4, 6, 8]], "expected_output": "[3, 4.00]"},
        {"input_data": [[8, 6, 4, 2]], "expected_output": "[3, 6.0]"},
        {"input_data": [[1, 100, 100, 100, 100]], "expected_output": "[1, 1.0]"},
        {"input_data": [[10, 10, 10, 10, 1]], "expected_output": "[4, 10.00]"},
        {"input_data": [[5, 5, 1, 1, 5, 5]], "expected_output": "[4, 3.00]"},
        {"input_data": [[1, 2, 3, 4, 5, 6]], "expected_output": "[5, 3.0]"},
        {"input_data": [[1, 1, 1, 1, 1, 10]], "expected_output": "[5, 1.00]"},
        {"input_data": [[10, 10, 10, 1, 1]], "expected_output": "[4, 7.75]"},
        {"input_data": [[1, 1, 10, 10, 10, 10]], "expected_output": "[2, 1.00]"},
        {"input_data": [[10, 1, 100, 1]], "expected_output": "[3, 37.0]"},
        {"input_data": [[2, 4, 8, 16, 32]], "expected_output": "[4, 7.50]"},
        {"input_data": [[100, 2, 2, 2, 2]], "expected_output": "[4, 26.5]"},
        {"input_data": [[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]], "expected_output": "[9, 2.78]"},
        {"input_data": [[1, 1, 10, 10, 1, 10, 10, 1]], "expected_output": "[7, 6.14]"},
        {"input_data": [[10, 20, 30, 40, 50, 1]], "expected_output": "[5, 30.00]"},
    ],
    "The Rolling Turbulence Index (Time Series)": [
        {"input_data": [[], 10], "expected_output": "-1"},
        {"input_data": [[5], 0], "expected_output": "0"},
        {"input_data": [[1, 1, 1, 1, 1], 0], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4], 0], "expected_output": "0"},
        {"input_data": [[10, 1, 2, 3], -1], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4, 5], 4], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4, 5], 3], "expected_output": "0"},
        {"input_data": [[10, 11, 12, 13, 14], 100], "expected_output": "0"},
        {"input_data": [[1, 1, 2, 2, 3, 3], 2], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4, 5], 10], "expected_output": "0"},
        {"input_data": [[100, 1, 2, 3, 100], 2], "expected_output": "1"},
        {"input_data": [[10, 20, 1, 1, 1, 1, 30, 40], 0], "expected_output": "2"},
        {"input_data": [[50, 1, 2, 3, 4, 50], 3], "expected_output": "1"},
        {"input_data": [[10, 5, 6, 7, 8, 9, 20], 4], "expected_output": "1"},
        {"input_data": [[1, 50, 2, 3, 4, 50], 2], "expected_output": "2"},
        {"input_data": [[100, 90, 80, 1, 2, 3, 4], 3], "expected_output": "3"},
        {"input_data": [[5, 10, 15, 20, 1, 1], 0], "expected_output": "4"},
        {"input_data": [[50, 50, 50, 1, 2, 3], 1], "expected_output": "0"},
        {"input_data": [[10, 1, 2, 3, 4, 5], 4], "expected_output": "1"},
        {"input_data": [[10, 5, 2, 1], 3], "expected_output": "1"},
        {"input_data": [[10, 1, 10, 1], 10], "expected_output": "0"},
        {"input_data": [[1, 10, 1, 10, 1], 15], "expected_output": "0"},
        {"input_data": [[1, 20, 2, 3], 10], "expected_output": "2"},
        {"input_data": [[1, 100, 2, 100, 3], 50], "expected_output": "0"},
        {"input_data": [[1, 1, 100, 1, 1], 0], "expected_output": "0"},
        {"input_data": [[-1, -2, -3, -4], 2], "expected_output": "0"},
        {"input_data": [[-10, -5, 0, 5, 10], 10], "expected_output": "0"},
        {"input_data": [[0, -5, -10, -15], 10], "expected_output": "0"},
        {"input_data": [[10, -10, 10, -10], 20], "expected_output": "0"},
        {"input_data": [[-5, -5, 10, 10], 0], "expected_output": "0"},
        {"input_data": [[1, 2, 1, 2, 1, 2], 1], "expected_output": "0"},
        {"input_data": [[10, 11, 20, 21, 30, 31], 1], "expected_output": "0"},
        {"input_data": [[1, 2, 10, 11, 20, 21], 1], "expected_output": "0"},
        {"input_data": [[5, 6, 100, 7, 8], 1], "expected_output": "0"},
        {"input_data": [[10, 11, 10, 11], 1], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4, 5], 1], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4, 5], 2], "expected_output": "0"},
        {"input_data": [[10, 0, 1, 2, 3, 10], 5], "expected_output": "1"},
        {"input_data": [[5, 1, 2, 3, 4, 5], 4], "expected_output": "1"},
        {"input_data": [[1, 10, 2, 3], 9.9], "expected_output": "1"},
        {"input_data": [[1, 2, 3, 4], 2.9], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4], 3.0], "expected_output": "0"},
        {"input_data": [[1, 2, 3, 4], 3.1], "expected_output": "0"},
        {"input_data": [[10, 11, 12, 13], 1.5], "expected_output": "0"},
        {"input_data": [[0, 0.5, 1.0, 1.5], 1.0], "expected_output": "0"},
        {"input_data": [[1, 10, 1, 10, 1, 10, 1], 18], "expected_output": "0"},
        {"input_data": [[1, 1, 10, 1, 1, 1], 1], "expected_output": "3"},
        {"input_data": [[100, 10, 5, 1, 50, 100], 10], "expected_output": "1"},
        {"input_data": [[10, 9, 8, 7, 6], 3], "expected_output": "0"},
        {"input_data": [[10, 20, 30, 1, 2, 3, 4, 5], 4], "expected_output": "3"},
    ],
    "Percy the Penguin's Apple Adventure": [
        {"input_data": [["A", "Window", "B", "Window"]], "expected_output": "2"},
        {"input_data": [["Door", "Long Win dow", "Wall", "W I N D O W"]], "expected_output": "0"},
        {"input_data": [["Window 12", "Window", "Window 12", "Window"]], "expected_output": "2"},
        {"input_data": [["W", "A Window B", "Z", "A Window B"]], "expected_output": "2"},
        {"input_data": [["Window", "Window", "Window", "Window"]], "expected_output": "2"},
        {"input_data": [["Z", "Window"]], "expected_output": "1"},
        {"input_data": [["Door", "window", "Wall"]], "expected_output": "1"},
        {"input_data": [["W", "WIN DOW X Y", "Z"]], "expected_output": "0"},
        {"input_data": [["Window 1234", "Door", "X", "Window 1234"]], "expected_output": "1"},
        {"input_data": [["A Window A", "B", "C", "D"]], "expected_output": "0"},
        {"input_data": [["Z", "WNDW"]], "expected_output": "0"},
        {"input_data": [["A", "Door", "B", "Gate"]], "expected_output": "0"},
        {"input_data": [["W", "Wall", "W", "WIND"]], "expected_output": "0"},
        {"input_data": [["A Window B", "Not a Door", "X", "Not Window"]], "expected_output": "0"},
        {"input_data": [["Door", "Window 12", "Wall", "WNDW 12"]], "expected_output": "1"},
        {"input_data": [["Z", "The Window"]], "expected_output": "0"},
        {"input_data": [["A", "Wind ow 1"]], "expected_output": "0"},
        {"input_data": [["Z", "W I N D O W 1"]], "expected_output": "0"},
        {"input_data": [["Door", "Window 1", "Wall", "The Window"]], "expected_output": "0"},
        {"input_data": [["Window", "Window 1", "Window", "Window 2"]], "expected_output": "0"},
        {"input_data": [["Window", "Z"]], "expected_output": "0"},
        {"input_data": [["W I N D O W", "A", "W I N D O W"]], "expected_output": "0"},
        {"input_data": [["Z", "Z", "Window 12"]], "expected_output": "0"},
        {"input_data": [["Window 12", "X", "Window 12", "Y"]], "expected_output": "0"},
        {"input_data": [["Door", "A Window B", "Window 12"]], "expected_output": "1"},
        {"input_data": [["Door", "A Window B", "Wall", "The Window"]], "expected_output": "1"},
        {"input_data": [["Window 1", "Window", "Window 1", "Window"]], "expected_output": "2"},
        {"input_data": [["Window 12", "Window 1", "Window 12", "Window"]], "expected_output": "1"},
        {"input_data": [["Window", "Window 123", "Window", "Window 123"]], "expected_output": "0"},
        {"input_data": [["Window", "Door", "Window 12", "Door"]], "expected_output": "0"},
        {"input_data": [["X", "WWWWWW"]], "expected_output": "0"},
        {"input_data": [["X", "A WINDOW B C"]], "expected_output": "0"},
        {"input_data": [["Z", "WINDOW"]], "expected_output": "1"},
        {"input_data": [["Z", "WIND OW 12"]], "expected_output": "0"},
        {"input_data": [["Z", "WINDOW 123"]], "expected_output": "0"},
        {"input_data": [["Window", "X", "Y", "Window"]], "expected_output": "1"},
        {"input_data": [["X", "Window", "Y", "Window"]], "expected_output": "2"},
        {"input_data": [["Window", "Window", "Window", "Window", "Window"]], "expected_output": "2"},
        {"input_data": [["X", "Window", "X", "Window", "X", "Window"]], "expected_output": "3"},
        {"input_data": [["W", "winDOw"]], "expected_output": "1"},
        {"input_data": [["W", "WInDo W"]], "expected_output": "0"},
        {"input_data": [["W", "W I N D O W"]], "expected_output": "0"},
        {"input_data": [["W", "w i n d o w 1"]], "expected_output": "0"},
        {"input_data": [["w", "a window b"]], "expected_output": "1"},
        {"input_data": [[]], "expected_output": "0"},
        {"input_data": [["W"]], "expected_output": "0"},
        {"input_data": [["W", "X"]], "expected_output": "0"},
        {"input_data": [["Window 12"]], "expected_output": "0"},
        {"input_data": [["A", "Window"]], "expected_output": "1"},
    ],
    # Add more test cases for other problems here
}
